### ISSUE TITLE
DSD suport over I2S on Rpi

### ISSUE THREAD

**Issue by denisbalog** [lintweaker/mpd-dsd-019#1]
Hi Lintweaker,

First thanks for mpd-dsd contribution.

I would ask you what is the reason RPI doesn't send native (not DoP) DSD files over i2s?
Is it possible to implement, and which part of a chain is problematic, ALSA driver, Kernel, MPD?
I have a DAC that supports native DSD over I2S lines, but not DoP.
And looking into i don't see the reason it should not work.

Thanks in advance,

D.

**Comment by lintweaker** [comment]
Hi D.

Glad you like it. For native DSD to work on the RPI its ALSA driver should support the native DSD sample format. For DSD to work the I2S pin functions also have to change, not sure if the PI can handle that.

**Comment by denisbalog** [comment]
Thank you for quick reply,

I will try to investigate this further.

**Comment by 24century** [comment]
Make sense, looks like it is not possible at present time for DoP over I2S on RPI
