### ISSUE TITLE
enumeration value ‘DSD_U32’ not handled in switch

### ISSUE THREAD

**Issue by norrest** [lintweaker/mpd-dsd-019#11]
Hi) 
During "make"  i found error

src/output/plugins/RoarOutputPlugin.cxx:165:9:enumeration value ‘DSD_U32’ not handled in switch
mv -f src/output/plugins/.deps/liboutput_plugins_a-RoarOutputPlugin.Tpo src/output/plugins/.deps/liboutput_plugins_a-RoarOutputPlugin.Po
g++ -DHAVE_CONFIG_H -I.  -DNDEBUG -I./src -pthread -isystem /usr/include/glib-2.0 -isystem /usr/lib/arm-linux-gnueabihf/glib-2.0/include -I/usr/include -DSYSTEM_CONFIG_FILE_LOCATION='"/usr/local/etc/mpd.conf"'  -I/usr/include/alsa   -I/usr/include/AL   -D_REENTRANT  -pthread  -D_GNU_SOURCE -std=gnu++0x -pthread -g -O2 -fvisibility=hidden -fno-threadsafe-statics -fmerge-all-constants -fno-exceptions -fno-rtti -ffast-math -ftree-vectorize -ffunction-sections -fdata-sections -Wall -Wextra -Wmissing-declarations -Wshadow -Wpointer-arith -Wcast-qual -Wwrite-strings -Wsign-compare -MT src/output/plugins/liboutput_plugins_a-AoOutputPlugin.o -MD -MP -MF src/output/plugins/.deps/liboutput_plugins_a-AoOutputPlugin.Tpo -c -o src/output/plugins/liboutput_plugins_a-AoOutputPlugin.o `test -f 'src/output/plugins/AoOutputPlugin.cxx' || echo './'`src/output/plugins/AoOutputPlugin.cxx

**Comment by lintweaker** [comment]
Hi,
I've never heard of RoarAudio. It should compile normally if you do not enable that plugin.

**Comment by norrest** [comment]
ok) its only for statistic!
