### ISSUE TITLE
dsd-native patch for mpd-git

### ISSUE THREAD

**Issue by mistepien** [lintweaker/mpd-dsd-019#13]
I would be great if You could clone mpd-git and maintance dsd version of mpd-git.

**Comment by mistepien** [comment]
In mpd-git many nice thinks have happened. For instance null_mixer, good soxr_resample configuration and many others. BTW, maintance of mpd-git would be continuous. In case of release 0.20 your patch would be already there.

**Comment by hicaoc** [comment]
mpd-git support dsd-native ,do not need patch

**Comment by norrest** [comment]
@hicaoc 

I try to install git, but in settings something wrong! 
I cant run Native mode

**Comment by norrest** [comment]
And how to select native mode 0 or 2 ?

**Comment by lintweaker** [comment]
MPD 0.20 git seems to support al the needed DSD formats. Closing this issue

**Comment by norrest** [comment]
how to select native mode 0 or 2 ?

**Comment by lintweaker** [comment]
This is not a support forum for MPD 0.20. 

My version of MPD 0.19 + DSD patch only supports DSD_U32_BE. My version of MPD 0.18 + DSD patch supports both BE and LE formats.

**Comment by norrest** [comment]
i am sorry,  but why u cant create patch for support LE format in 0.19 version?
