### ISSUE TITLE
patch for MPD 0.19.16 released

### ISSUE THREAD

**Issue by norrest** [lintweaker/mpd-dsd-019#23]
Hi! Can you create patch for MPD 0.19.16 released?
Thank you!

**Comment by norrest** [comment]
in ver 0.19.16 (2016/06/13)
 faster seeking

may be this fix clics during switch/forward track`s!

**Comment by lintweaker** [comment]
Patch is up, no changes from the previous version (so no fix for hang with B1...dff)

**Comment by norrest** [comment]
May be need force CUT last 0.05 sec of file?
