### ISSUE TITLE
 hang with Music Player Daemon 0.19.14-dsd with certain DSD DSDIFF songs

### ISSUE THREAD

**Issue by norrest** [lintweaker/mpd-dsd-019#24]
https://github.com/lintweaker/mpd-dsd-019/issues/18 
like this! 
But with version 0.19.14

**Comment by lintweaker** [comment]
So what is it? Hang or crash? Very different things.

**Comment by norrest** [comment]
Files the same with previously! And again the same symptoms! 
Help only kill -9 

top - 18:58:05 up  2:50,  1 user,  load average: 1.26, 0.73, 0.87
Tasks: 105 total,   2 running, 103 sleeping,   0 stopped,   0 zombie
%Cpu(s):  6.6 us, 43.5 sy,  0.0 ni, 49.4 id,  0.0 wa,  0.5 hi,  0.0 si,  0.0 st
KiB Mem:   1030152 total,  1011596 used,    18556 free,   133740 buffers
KiB Swap:        0 total,        0 used,        0 free.   779700 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
17303 mpd        1   0  113940  22416  14756 S  99.1  2.2   1:31.21 mpd
20608 root       7   0    4584   2108   1696 R   1.0  0.2   0:00.06 top

mpc stop
error: Timeout

Jun 23 19:00:10 localhost systemd[1]: Stopping Music Player Daemon...
Jun 23 19:01:41 localhost systemd[1]: mpd.service stop-sigterm timed out. Killing.
Jun 23 19:01:41 localhost systemd[1]: mpd.service: main process exited, code=killed, status=9/KILL
Jun 23 19:01:41 localhost systemd[1]: Stopped Music Player Daemon.
Jun 23 19:01:41 localhost systemd[1]: Unit mpd.service entered failed state.

**Comment by norrest** [comment]
http://dropmefiles.com/taGLe 
test file!

**Comment by lintweaker** [comment]
okay, got the file. Indeed it hangs at the end, but this file (B1 ....dff) does not hit the normal 'DSD sample size not dividable by 4 bug'. This is a new one. Need to investigate..
Where do you keep getting these ill formed DSD files :-)

**Comment by norrest** [comment]
))) 
Can u create patch for latest MPD 0.19.16 ? I will test it to!!!

**Comment by norrest** [comment]
May be need force CUT last 0.05 sec of file?

**Comment by norrest** [comment]
http://www.daphile.com/gpl-src/00-Daphile-patches/squeezelite/13-remove_last_block_zero_padding.patch
Can it help?
