### ISSUE TITLE
DSD_U32_LE and DSD_U32_LE both support in patch

### ISSUE THREAD

**Issue by norrest** [lintweaker/mpd-dsd-019#26]
I have created the task,
https://bugs.musicpd.org/view.php?id=4546
But I see that DSD_U32_BE supported only in git (0.20) version.
How can I explain to developers what is not in 019_?
Or I something wrong?
May be easier to add support in your main patch? 
*_DSD_U32_LE important for Amanero**

**Comment by norrest** [comment]
Hi! 
cirrus  (administrator) 
2016-07-29 08:55

MPD 0.20 (git master) supports both DSD_U32_BE and DSD_U32_LE.

Can you create patch for git version? 

https://github.com/lintweaker/mpd-dsd-019/issues/13

**Comment by lintweaker** [comment]
As MPD 0.20 git now has both DSD_U32_BE and DSD_U32_LE support I'll close this issue.
