### ISSUE TITLE
MPD 0.20.2 patch

### ISSUE THREAD

**Issue by norrest** [lintweaker/mpd-dsd-019#30]
Hi! 
Can you craete patch for MPD 0.20.2 ?
Who will work with parameters 
DOP on 
DOP off
DSD_native on

**Comment by lintweaker** [comment]
Hi,
No sorry. Only patches for MPD 0.19. DSD support in MPD 0.20 should be sufficient

**Comment by norrest** [comment]
Maybe some tweaks? I don know how switch vs  dop/ dsd native and all above off! (
