### ISSUE TITLE
Support for PCM --> DSD upsampling 

### ISSUE THREAD

**Issue by olm52** [lintweaker/mpd-dsd-019#6]
Thank you for your good work!

It would be very nice if mpd-dsd could support the new branch of sox with PCM --> DSD upsampling (patching Sox Resampler.cxx)

https://github.com/mansr/sox
http://www.computeraudiophile.com/f11-software/direct-stream-digital-encoding-sox-25556/

A package sox-dsd-git is already available for archlinux at
https://aur.archlinux.org/packages/sox-dsd-git/
I have also made yesterday a package for mpd-dsd 019 with your patch here
https://aur.archlinux.org/packages/mpd-dsd/

**Comment by lintweaker** [comment]
Nice!
Good to have a way to do DSD upsampling on Linux.
I did a few testruns outputting DSD64 and DSD128, it takes quite a while to convert a FLAC file to DSD. Realtime conversion does not seem to be possible with the current sox SDM code.

**Comment by olm52** [comment]
According to the developer the option "fast" is "Reasonably good quality while fast enough for real-time operation. This is the default."
Example:
sox PCM44.flac DSD64.dsf rate -v 2822400 sdm -f fast

Available options (from fast to very slow)
fast
hq
audiophile
goldenear
