### ISSUE TITLE
update for new versions

### ISSUE THREAD

**Issue by norrest** [lintweaker/mpd-dsd-019#7]
Hi!
If i patch @core@ then update, shall i need to do this again if publish new version of MPD?
Or I need just upgrade MPD?

**Comment by lintweaker** [comment]
Hello,
Not sure what you mean here.

**Comment by norrest** [comment]
If i install kernel with @patch for MPD 0.19.10@ 
Can i shall update MPD to newest versions?

**Comment by lintweaker** [comment]
The kernel does not have patches for MPD. MPD is a user space program.
When updating the kernel you do no have to update MPD.

**Comment by norrest** [comment]
Can i shall update MPD to newest versions? Or neep again usin patch!

**Comment by lintweaker** [comment]
You do not have to update to the latest MPD version if you do not hit any bugs. My latest DSD patch is against MPD 0.19.10. You always need to get a clean version of MPD then use the patch with the matching version.
