### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by norrest** [lintweaker/mpd-dsd-019#8]
Hi Again!

(Stripping trailing CRs from patch; use --binary to disable.)
can't find file to patch at input line 5
Perhaps you used the wrong -p or --strip option?
## The text leading up to this was:

|diff --git a/Makefile.am b/Makefile.am
|index 89819de..dedc881 100644
|--- a/Makefile.am
## |+++ b/Makefile.am

File to patch:

**Comment by lintweaker** [comment]
Hi,
Have you even tried other -p options? -p1 should do the trick

**Comment by norrest** [comment]
After  running the next command with the option –p1:

root@volumio:/usr/src/linux-4.3# patch -p1 < volumio.patch

we get the next message:

(Stripping trailing CRs from patch; use --binary to disable.)
can't find file to patch at input line 5
Perhaps you used the wrong -p or --strip option?

## The text leading up to this was:

|diff --git a/Makefile.am b/Makefile.am
|index 89819de..dedc881 100644
|--- a/Makefile.am

## |+++ b/Makefile.am

File to patch:

**Comment by lintweaker** [comment]
It seems you are trying to patch a kernel. Sorry, this has no relationship with MPD and does not belong here.
